### ISSUE TITLE
R 3.6.0?

### ISSUE THREAD

**Issue by GitHubDoug** [y1zhou/brendaDb#13]
> BiocManager::install("brendaDb", dependencies=TRUE)
Bioconductor version 3.9 (BiocManager 1.30.10), R 3.6.0 (2019-04-26)
Installing package(s) 'brendaDb'

Warning message:
"package ‘brendaDb’ is not available (for R version 3.6.0) "

Can this be resolved? Your package appears to do exactly what I need.

**Comment by y1zhou** [comment]
@GitHubDoug You may need to update your `Bioconductor` to the latest version (3.10). Alternatively, you can install the package directly from this GitHub repo by `devtools::install_github("y1zhou/brendaDb")` as it's a newer version.

Thanks for using this package and please let me know if there's any further questions!

**Comment by GitHubDoug** [comment]
Ran some updates, got it installed via R, now running through RStudio, thanks!
I really appreciate your work.

**Comment by y1zhou** [comment]
Glad it worked out for you!
